name: Build iOS Dev version
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Code quality CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macos-10.15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - run: yarn install

      - name: Install Dependencies
        run: |
          cd ios
          pod install --repo-update
        shell: bash
        
      - name: Install Gems
        run: bundle install

      - name: Build iOS
        run: bundle exec fastlane ios beta
        env:
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
